#! /usr/bin/env bash

function usage {
  echo "Usage: aoc [DIRECTORY]"
}

docker images | grep aoc22 > /dev/null 2>&1 || docker build . -t aoc22:latest

if [ -z "$1" ]
then
  usage
  exit 1
fi

docker run -v `pwd`/$1:/workspace aoc22 lua solution.lua
